### ISSUE TITLE
couple of small issues r.e. advanced html and the build script

### ISSUE THREAD

**Issue by ezkialrage** [nicklansley/nick-stable-diffusion#2]
[NUAL] - line 140 of advanced.html should be removed `}` dangling closing bracket.

for the build script, i had to comment out the section of `building the frontend` that deals with css files.  i was getting an error saying no .css files in the directory so it failed to compile and errored out.  commenting that out, and it built fine.  You might think of seeding the directory with an empty skeleton css file or `if` statementing the css check.

other than that, got it up and running! can only do 348x348 images with a geforce 1080 though :( but it works well.  5-10 second image renders.

**Comment by nicklansley** [comment]
Thanks @ezkialrage ! I have removed the CSS copy as CSS is now inside the HTML pages, and removed that dangling bracket.

Excellent news on running it on a 1080 - my aim was to get this app running on all kinds of PC hardware so I'm glad you've had success!
