### ISSUE TITLE
Links in installation not working

### ISSUE THREAD

**Issue by j-brammer** [nicklansley/nick-stable-diffusion#3]
The following links don't appear to exist in the installation documentation:

- https://github.com/nicklansley/nick-stable-diffusion/releases/download/untagged-2dbe8c6c907347f4a117/detection_Resnet50_Final.pth (104 MB)
- https://github.com/nicklansley/nick-stable-diffusion/releases/download/untagged-2dbe8c6c907347f4a117/RealESRGAN_x4plus.pth (64 MB)
- https://github.com/nicklansley/nick-stable-diffusion/releases/download/untagged-2dbe8c6c907347f4a117/parsing_parsenet.pth (82 MB)
- https://github.com/nicklansley/nick-stable-diffusion/releases/download/untagged-2dbe8c6c907347f4a117/GFPGANv1.4.pth (332 MB)

**Comment by nicklansley** [comment]
Hi

Apologies, I'm not sure why those links are no longer available. First thing Monday I'll upload these model files to my own CDN and update the links. I'll let you know when it's done - apologies in the meantime.

Cheers
Nick

**Comment by nicklansley** [comment]
HI,

I have updated the URL paths to the model files in README.md but for your convenience they are here too:
- [detection_Resnet50_Final.pth](https://lansleycom.blob.core.windows.net/cdn-lansley-com/nsd_models/detection_Resnet50_Final.pth) (104 MB)
- [RealESRGAN_x4plus.pth](https://lansleycom.blob.core.windows.net/cdn-lansley-com/nsd_models/RealESRGAN_x4plus.pth) (64 MB)
- [parsing_parsenet.pth](https://lansleycom.blob.core.windows.net/cdn-lansley-com/nsd_models/parsing_parsenet.pth) (82 MB)
- [GFPGANv1.4.pth](https://lansleycom.blob.core.windows.net/cdn-lansley-com/nsd_models/GFPGANv1.4.pth) (332 MB)
